### ISSUE TITLE
Using React Native

### ISSUE THREAD

**Issue by salah-saleh** [dashevo/dashwallet-ios#90]
Hey, 
I want to ask about the decision of separating the ios and android development. Did you guys consider using react native? I think that would have saved so much time, help stability accross platform and reach wider set of mobile developers. Edge wallet is a famous wallet that took this approach and is very successful: https://github.com/EdgeApp
Also I want to ask about the mechanism with which the Evolution wallet will store the usernames and passwords and how will they be connected to the Public/Private key? I kind imagine it like how the Edge wallet work, but correct me if I am wrong:
https://support.edge.app/support/solutions/articles/8000058708-why-do-i-need-a-login-password-to-use-the-edge-wallet- 
https://support.edge.app/support/solutions/articles/8000058674-how-to-maximize-my-edge-account-security-

Thank you!

**Comment by QuantumExplorer** [comment]
We currently have 2 directions in development, a react native wallet, and native wallets as well, this is because we eventually want to offer broad coverage of libraries and example implementations to our partners. However I can assure you that from the experience of last year, the native wallets are moving ahead with very nice progress.

**Comment by salah-saleh** [comment]
Thanks for the response. What about the second question?
